# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status_CS',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status_FIFA',
        ),
    ]
