# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_info',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
