# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='here', verbose_name='avatar'),
        ),
    ]
