# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171101_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('firstName', models.CharField(default=None, max_length=50)),
                ('lastName', models.CharField(default=None, max_length=50)),
                ('emailID', models.CharField(default=None, max_length=50)),
                ('institution', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='player',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_head',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='no_of_players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_name',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='numberOfPlayers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournamentDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournamentName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.Tournament'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.Tournament'),
        ),
        migrations.AddField(
            model_name='team',
            name='teamHead',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.User'),
        ),
    ]
