# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180212_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_lock',
            new_name='locked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team_cs',
        ),
        migrations.RemoveField(
            model_name='team',
            name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_avatar',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_head',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='portal/team_logo'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='portal.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
