# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180214_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='avatar',
        ),
    ]
