# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_team_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=portal.models.avatar_upload, verbose_name='avatar'),
        ),
    ]
