# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_team_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamnotification',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeamNotification',
        ),
    ]
