# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180215_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steam_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='steam_connected',
            field=models.BooleanField(default=False),
        ),
    ]
