# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0007_auto_20171111_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(default=None, max_length=200, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamHead',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamName',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='numberOfPlayers',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournamentDate',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournamentName',
        ),
        migrations.AddField(
            model_name='player',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_head',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='no_of_players',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Tournament'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Tournament'),
        ),
    ]
