# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20171206_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
