# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_profile_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_CS',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_DOTA',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_FIFA',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
