# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20171208_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game_on',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='player1',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='player2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='player3',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='player4',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='player5',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
