# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_teamnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_cs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_lock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
