# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20180209_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player5',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='number_of_players',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_avatar',
            field=models.ImageField(blank=True, upload_to='team_image'),
        ),
    ]
